server:
  port: 6789
  servlet:
    context-path: /es
    jsp:
      init-parameters:
        development: true
mybatis:
  type-aliases-package: home.entity
  mapper-locations: classpath:mapper/*Mapper.xml
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ems
    username: root
    password: root
  mvc:
    view:
      prefix: /
      suffix: .jsp
    date-format: yyyy-MM-dd
  jackson:
    date-format: yyyy-MM-dd
logging:
  level:
    root: error